server:
  port: 9090



# Database configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root   # MySQL Workbench username
    password: Zxy@5628610 # MySQL Workbench password
    url: jdbc:mysql://localhost:3309/fyp_fitness?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # AI service configuration
  ai:
    deepseek:
      url: https://api.siliconflow.cn/v1/chat/completions
      api-token: sk-teuivpffjzajnpulzvytghljvbaymtunthinwnxcizxgitjp
      model: deepseek-ai/DeepSeek-V2.5

  # Mail Service
  mail:
    host: smtp.mailersend.net
    port: 587
    username: MS_bWM0Iq@trial-3yxj6ljkmqxgdo2r.mlsender.net
    password: mssp.FlYyYxN.z86org8y6n1lew13.rcSe2P4
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
    sender:
      email: MS_bWM0Iq@trial-3yxj6ljkmqxgdo2r.mlsender.net
      name: Gym Panel Team

# Configure mybatis entity and xml mapping
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# Pagination
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

ip: localhost